### PR TITLE
Use event repository for retrieving events

### PR DESCRIPTION
**Pull request by psrpinto**
> Apologies in advance for the high number of commits. If you review commit-by-commit, it should be relatively easy to review., a lot of the commits are very simple.

This PR is the conclusion of the event repository effort. In #188 we made it so that creating/updating/deleting events happens through the event repository. In this PR, we make it so that retrieving events also happens through the event repository.

With this PR, all access to events now happens through the event repository.

## Summary of changes

- Use `get_*()` methods from `Event_Repository` everywhere, instead of `get_posts()` or `WP_Query()`
- Add missing `get_*()` methods in `Event_Repository`
  - Not all needed methods were present yet
- Fix issues in some of the `get_*()` methods in `Event_Repository`
  - `Event_Repository` is now doing the same queries that were being done prior to this PR, so that this PR behaves the same as the previous code.
- Make it so that pagination handling is done only in the `execute_events_query()` method.
    - No need to call `assert_pagination_arguments()` in individual methods any more.

## Testing instructions

Test creating, editing, deleting and viewing events.

### CODE REVIEW

**Comment by psrpinto** [comment]
Currently there are four failing tests, which fail due to inconsistencies in UTC/timezone when creating events. These tests are also failing on trunk, so the failures were not introduced in this PR.

EDIT: Tests fixed in #191

**Review by trymebytes — COMMENTED** [review]
Tried testing but I got this error on loading the `/events` route
```
Notice: Undefined offset: 0 in /Users/tosinoguntuyi/Sites/localwp/wp-content/plugins/wporg-gp-translation-events/includes/event/event-repository-cached.php on line 74

Fatal error: Uncaught TypeError: Argument 1 passed to Wporg\TranslationEvents\Event\Events_Query_Result::__construct() must be of the type array, null given,
```

**Comment by amieiro** [comment]
> Tried testing but I got this error on loading the `/events` route
> 
> ```
> Notice: Undefined offset: 0 in /Users/tosinoguntuyi/Sites/localwp/wp-content/plugins/wporg-gp-translation-events/includes/event/event-repository-cached.php on line 74
> 
> Fatal error: Uncaught TypeError: Argument 1 passed to Wporg\TranslationEvents\Event\Events_Query_Result::__construct() must be of the type array, null given,
> ```

The tests are working fine for me.

image

**Comment by psrpinto** [comment]
> Fatal error: Uncaught TypeError: Argument 1 passed to Wporg\TranslationEvents\Event\Events_Query_Result::__construct() must be of the type array, null given,

Thanks both for testing :) I'm working on a fix for this issue.

**Comment by psrpinto** [comment]
I believe the issue is now fixed, could you test again @trymebytes?

**Comment by trymebytes** [comment]
I now get this
`Fatal error: Uncaught Wporg\TranslationEvents\Event\InvalidTitle: Event title is invalid in wporg-gp-translation-events/includes/event/event.php:145`

**Comment by psrpinto** [comment]
> Fatal error: Uncaught Wporg\TranslationEvents\Event\InvalidTitle: Event title is invalid in wporg-gp-translation-events/includes/event/event.php:145

This was because we're now making sure that events have a title, but there may exist events in the database (that were created prior to this PR) that don't have a title. I've now fixed this issue.

**Review by trymebytes — APPROVED** [review]
Tested and works for me!

**Pull request merged**
