### PR TITLE
Improve i18n of the plugin

### PR DESCRIPTION
**Pull request by pedro-mendonca**
- [x] Add missing gettext wrappers
- [x] Use `wp_sprintf()` to properly use arrays of items to list.

### CODE REVIEW

**Review by akirk — APPROVED** [review]

**Review by trymebytes — APPROVED** [review]

**Comment by pedro-mendonca** [comment]
Fixed the conflicts from rebasing. Please review again.

**Review by psrpinto — CHANGES_REQUESTED** [review]
Thanks for this!

I'm getting an array to string conversion error in the "View stats summary in text" section:

Screenshot 2024-04-18 at 17 32 54

I took a quick look at what the cause might be but wasn't able to figure it out yet.

**Comment by pedro-mendonca** [comment]
@psrpinto found the issue, on fixing conflicts I've inadvertently removed the `%l`
Comminting the fix now.

**Review by psrpinto — APPROVED** [review]
Works well!

**Pull request merged**
