### PR TITLE
Toggle the usernames

### LINKED ISSUE #219: Add a toggle to display/hide the action buttons on attendees for cohosts
The many "Make cohost" buttons are a bit overwhelming.

Screenshot 2024-04-17 at 14 18 53

### PR DESCRIPTION
**Pull request by trymebytes**
Fixes #219. In this PR we show or hide the co-host buttons by clicking on a check box.

### CODE REVIEW

**Comment by psrpinto** [comment]
Instead of adding this button, could we instead add the list of attendees to the edit page (with the make/remove host buttons), and remove the buttons from the details page? I think managing hosts should be done from the edit page. I mentioned this in https://github.com/WordPress/wporg-gp-translation-events/issues/219#issuecomment-2061524631

**Comment by trymebytes** [comment]
Thank you @psrpinto, I just read the linked comment and it makes sense to not manage hosts and attendees on the event page. Here's a mockup, I'm considering;
Screenshot 2024-04-19 at 11 54 10

**Comment by akirk** [comment]
I was thinking of something much more simple and ephermal. Clicking the headline could toggle it.
list-toggle

```diff
--- a/assets/css/translation-events.css
+++ b/assets/css/translation-events.css
@@ -361,6 +361,12 @@ ul.text-snippets {
 ul#translation-links li {
        margin-bottom: .5em;
 }
+.icons li .name {
+       display: none;
+}
+.icons li  {
+       width: auto !important;
+}
 
 /* show the event-details-right below instead of on the right on mobile */
 @media (max-width: 768px) {
diff --git a/assets/js/translation-events.js b/assets/js/translation-events.js
index 9fe2bc6..e5411e5 100644
--- a/assets/js/translation-events.js
+++ b/assets/js/translation-events.js
@@ -38,6 +38,14 @@
                                                textArea.val( textAreaContent + $( this ).data( 'snippet' ) );
                                        }
                                );
+
+                               $( '.event-attendees h2, .event-contributors h2' ).on(
+                                       'click',
+                                       function ( e ) {
+                                               e.preventDefault();
+                                               $(this).closest('body').toggleClass('icons');
+                                       }
+                               );
                        }
                );
```

**Comment by akirk** [comment]
For edit buttons it could be looping through 3 css classes.

**Comment by trymebytes** [comment]
@akirk could you please explain more about the edit buttons comment above

**Comment by akirk** [comment]
Well, I was thinking that there could be just multiple "view states" so that you can modify the view to something more compact or without edit buttons when you want to take a screenshot

**Comment by akirk** [comment]
Well, I was thinking that there could be just multiple "view states" so that you can modify the view to something more compact or without edit buttons when you want to take a screenshot

**Comment by trymebytes** [comment]
I see, thanks for clarifying.

**Comment by trymebytes** [comment]
I think this might not need to go in the edit form, I suppose. Another thing is should this state be persisted for a specific event or for the user(such that all their events maintain the view state set)

**Review by psrpinto — APPROVED** [review]
Tested and it works 👍

**Comment by trymebytes** [comment]
Thanks @psrpinto!

**Pull request merged**
