### PR TITLE
Lint JS and CSS

### PR DESCRIPTION
**Pull request by psrpinto**
This is the final linting PR. It's mostly just fixing whitespace. In the js, I refactored a little to extract functions out of functions.

This will likely cause conflicts with #74. I can help resolve conflicts there, or it if gets merged, I will resolve conflicts here.

[Diff ignoring whitespace changes](https://github.com/WordPress/wporg-gp-translation-events/pull/85/files?diff=unified&w=1)

### CODE REVIEW

**Review by akirk — APPROVED** [review]
Looks good! I am just confused regarding the tooling, shall we add `wp-scripts` for this, like in https://github.com/GlotPress/gp-translation-helpers/blob/main/composer.json ?

**Comment by psrpinto** [comment]
> Looks good! I am just confused regarding the tooling, shall we add wp-scripts for this, like in https://github.com/GlotPress/gp-translation-helpers/blob/main/composer.json ?

(I'm assuming you meant [package.json](https://github.com/GlotPress/gp-translation-helpers/blob/main/package.json#L17-L18) instead of `composer.json`)

It didn't occur to me to use `wp-scripts`, good point. I'm willing to make the change to use `wp-scripts` instead of `phpcs`, if you think it makes sense.

Currently we don't yet have any npm/node dependencies, so we could consider sticking with `phpcs` for now. (Would save 384MB in the `node_modules/` 😅 ).

**Comment by psrpinto** [comment]
I rebased with trunk to fix conflicts.

**Comment by akirk** [comment]
> (I'm assuming you meant [package.json](https://github.com/GlotPress/gp-translation-helpers/blob/main/package.json#L17-L18) instead of composer.json)

Oops, indeed.

> Currently we don't yet have any npm/node dependencies, so we could consider sticking with phpcs for now.

I wasn't aware that phpcs can do this reformatting. I guess it's ok for the moment :-)

**Comment by psrpinto** [comment]
Ok, cool. I think it's a good time to merge this one now because there's only #74 which will be affected. Merging.

**Pull request merged**
